version: '3.8'

services:
  web:
    build: .
    ports:
      - "${HOST_PORT:-80}:80"
      - "${HOST_SSL_PORT:-443}:443"
    environment:
      # Flask Configuration
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-False}
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=${FLASK_PORT:-5000}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      
      # Database (SQLite - no external DB needed)
      - DATABASE_PATH=${DATABASE_PATH:-/app/data/app.db}
      
      # API Credentials
      - ZOOM_API_KEY=${ZOOM_API_KEY}
      - ZOOM_API_SECRET=${ZOOM_API_SECRET}
      - ZOOM_ACCOUNT_ID=${ZOOM_ACCOUNT_ID}
      - EVENTBRITE_PRIVATE_TOKEN=${EVENTBRITE_PRIVATE_TOKEN}
      
      # Google OAuth
      - GOOGLE_SSO_CLIENT_ID=${GOOGLE_SSO_CLIENT_ID}
      - GOOGLE_SSO_CLIENT_SECRET=${GOOGLE_SSO_CLIENT_SECRET}
      - ALLOWED_DOMAIN=${ALLOWED_DOMAIN:-ohvoice.org}
      
      # File Storage
      - UPLOAD_FOLDER=${UPLOAD_FOLDER:-/app/uploads}
      - DOWNLOAD_FOLDER=${DOWNLOAD_FOLDER:-/app/downloads}
      - CREDENTIALS_FOLDER=${CREDENTIALS_FOLDER:-/app/credentials}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-104857600}
      
      # YouTube
      - YOUTUBE_CHANNEL_ID=${YOUTUBE_CHANNEL_ID}
      - CHECK_EXISTING_VIDEOS=${CHECK_EXISTING_VIDEOS:-True}
      
      # Server Settings
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-300}
      
      # Domain and SSL
      - DOMAIN=${DOMAIN:-localhost}
      - USE_SSL=${USE_SSL:-False}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-/app/logs/app.log}
      
    volumes:
      - app_data:/app/data
      - app_uploads:/app/uploads
      - app_downloads:/app/downloads
      - app_credentials:/app/credentials
      - app_logs:/app/logs
      - ssl_certs:/etc/ssl/certs/custom
      
    restart: unless-stopped
    networks:
      - app-network

volumes:
  app_data:      # SQLite database and other data
  app_uploads:   # File uploads
  app_downloads: # Downloaded videos
  app_credentials: # API credentials and tokens
  app_logs:      # Application logs
  ssl_certs:     # SSL certificates

networks:
  app-network:
    driver: bridge
